#pragma checksum "..\..\..\CustomControls\Switch.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "EAD6F29DF51C53B74F1D62D3A8D35EFF"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using MetroStopStation.Converters;
using MetroStopStation.CustomControls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace MetroStopStation.CustomControls {
    
    
    /// <summary>
    /// Switch
    /// </summary>
    public partial class Switch : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "..\..\..\CustomControls\Switch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid containerGrid;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\CustomControls\Switch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition row0;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\CustomControls\Switch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition row1;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\CustomControls\Switch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition row2;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\CustomControls\Switch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition column0;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\CustomControls\Switch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition column1;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\CustomControls\Switch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition column2;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\CustomControls\Switch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition column3;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\CustomControls\Switch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition column4;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/MetroStopStation;component/customcontrols/switch.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\CustomControls\Switch.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 9 "..\..\..\CustomControls\Switch.xaml"
            ((MetroStopStation.CustomControls.Switch)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Switch_Loaded);
            
            #line default
            #line hidden
            
            #line 9 "..\..\..\CustomControls\Switch.xaml"
            ((MetroStopStation.CustomControls.Switch)(target)).SizeChanged += new System.Windows.SizeChangedEventHandler(this.Switch_SizeChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.containerGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.row0 = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 4:
            this.row1 = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 5:
            this.row2 = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 6:
            this.column0 = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 7:
            this.column1 = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 8:
            this.column2 = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 9:
            this.column3 = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 10:
            this.column4 = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

